---
title: "More About Me"
---

## Introduction
Hello, I'm a student studying currently at the University of British Columbia in the Masters of Data Science (Computational Linguistics).  I did my undergrad at University of Victoria, where I used primarily Python, with a Major in Computer Science and a Minor in Linguistics. There, I was first exposed to the basic foundations of AI and Machine Learning, at a time when Natural Language Processing was not yet in full swing as it is now; A result of this was a heavier focus on pre-NLP models and methods (Support vector machines, Bayesian nets, Hidden Markov Models, etc.), and a more casual overview of topics such as tokenization and NLP. 
Nevertheless, it was there that I developed the interest and curiosity in these topics that led me to take on the MDS-CL program. During this time, I also took on an internship, where I familiarized myself with the industry tools that are used, such as Git and Java servers utilizing the Spring Boot Framework. This gave me an insight on the actual business-related demands of LLMs, not just the theoretical capabilities.


## Future Goals
In the future, I hope to deepen my skills as someone who understands how AI models really work behind-the-scenes, and gain relevant experience from the capstone project for MDS-CL. I'm also looking forward to the career programming aspect that MDS-CL provides training on, as I understand that these aspects are not necessarily intuitive. These skills will help me persist in the Data Science field, which is ultimately the final goal.


## Hobbies
In my spare time, I enjoy Cooking, Baking, and Gardening. I'm especially a fan of trying out new recipes from cuisines that are unfamiliar to me, to see if there are good techniques or flavour combinations that could work as cross-cuisine fusions.
